class Constants:
    CROSSOVER_RATE = 0.5
    MUTATION_RATE = 0.5
    TOURNAMENT_SIZE = 5
    CHROMOSOME_LENGTH = 16
    GENE_LENGTH = 10
    SIMULATION_LENGTH = 100
    RANGE=[-10,10]
    EQUATION = lambda x:(x+10)*(x+10) -10